function mercatino(){var eb='',bb=' top: -1000px;',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',kb='");',Cb='#',Ob='&',oc='.cache.js',Eb='/',Kb='//',cc='0EA5936966FA6787CF120FCD9173404A',dc='126F932FFBEEEDC623D8EE800B325797',ec='3E4E69B3A3162326DC0FD6F40F12C0CA',gc='622E997C4F8124E27A2B440D9856138B',hc='65FC3F51B1FCE4522934FDF695DFB72C',ic='6F8A42D976571476596D663B3AFF4CF1',jc='7F95ACB3A6D45B89B461CCB700136FFA',kc='813A1B0CEC1EA0D41B37333ABEB90269',lc='913758239CAA467884F80BDF7503C259',nc=':',tb='::',Bc=':moduleBase',db='<!doctype html>',fb='<html><head><\/head><body><\/body><\/html>',wb='=',Db='?',yb='Bad handler "',cb='CSS1Compat',ib='Chrome',hb='DOMContentLoaded',Y='DUMMY',mc='E49092206BAF532C1E64AEDEA51A4F11',Ac='Ignoring non-whitelisted Dev Mode URL: ',Rb='Unexpected exception in locale detection, using default: ',Qb='_',zc='__gwtDevModeHook:mercatino',Pb='__gwt_Locale',yc='_gwt_dummy_',Jb='base',Hb='baseUrl',T='begin',Z='body',S='bootstrap',Gb='clear.cache.gif',vb='content',Mb='default',vc='end',jb='eval("',xc='file:',Zb='gecko',$b='gecko1_8',U='gwt.codesvr.mercatino=',V='gwt.codesvr=',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',pb='head',sc='href',wc='http:',Wb='ie10',Yb='ie8',Xb='ie9',$='iframe',Fb='img',fc='it_IT',mb='javascript',_='javascript:""',uc='jwolfgwt/jwolfgwt.css',pc='link',tc='loadExternalRefs',Lb='locale',Nb='locale=',W='mercatino',bc='mercatino.devmode.js',Ib='mercatino.nocache.js',sb='mercatino::',qb='meta',ob='moduleRequested',nb='moduleStartup',Vb='msie',rb='name',ab='position:absolute; width:0; height:0; border:none; left: -1000px;',qc='rel',Ub='safari',lb='script',ac='selectingPermutation',X='startup',rc='stylesheet',gb='undefined',_b='unknown',Sb='user.agent',Tb='webkit';var q=window;var r=document;t(S,T);function s(){var a=q.location.search;return a.indexOf(U)!=-1||a.indexOf(V)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:W,sessionId:q.__gwtStatsSessionId,subSystem:X,evtGroup:a,millis:(new Date).getTime(),type:b})}}
mercatino.__sendStats=t;mercatino.__moduleName=W;mercatino.__errFn=null;mercatino.__moduleBase=Y;mercatino.__softPermutationId=0;mercatino.__computePropValue=null;mercatino.__getPropMap=null;mercatino.__gwtInstallCode=function(){};mercatino.__gwtStartLoadingFragment=function(){return null};var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;var w=q.__gwt_activeModules=q.__gwt_activeModules||{};w[W]={moduleName:W};var A;function B(){D();return A}
function C(){D();return A.getElementsByTagName(Z)[0]}
function D(){if(A){return}var a=r.createElement($);a.src=_;a.id=W;a.style.cssText=ab+bb;a.tabIndex=-1;r.body.appendChild(a);A=a.contentDocument;if(!A){A=a.contentWindow.document}A.open();var b=document.compatMode==cb?db:eb;A.write(b+fb);A.close()}
function F(k){function l(a){function b(){if(typeof r.readyState==gb){return typeof r.body!=gb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(hb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(hb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=C();var f=B();var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(jb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(kb));g=f.createElement(lb);g.language=mb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(lb);g.language=mb;g.text=c[i];e.appendChild(g);d(e,g)}}}
mercatino.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;r.getElementsByTagName(pb)[0].appendChild(n)}
mercatino.__startLoadingFragment=function(a){return I(a)};mercatino.__installRunAsyncCode=function(a){var b=C();var c=B().createElement(lb);c.language=mb;c.text=a;b.appendChild(c);b.removeChild(c)};function G(){var c={};var d;var e;var f=r.getElementsByTagName(qb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,eb);if(j.indexOf(tb)>=0){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=eb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;mercatino.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=0?a.substring(0,d+1):eb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=v(Hb);if(a!=null){return a}return eb}
function h(){var a=r.getElementsByTagName(lb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return eb}
function i(){var a=r.getElementsByTagName(Jb);if(a.length>0){return a[a.length-1].href}return eb}
function j(){var a=r.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==eb){k=h()}if(k==eb){k=i()}if(k==eb&&j()){k=e(r.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return mercatino.__moduleBase+a}
function J(){var i=[];var j=0;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[Lb]=function(){var b=null;var c=Mb;try{if(!b){var d=location.search;var e=d.indexOf(Nb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Ob,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(Lb)}if(!b){b=q[Pb]}if(b){c=b}while(b&&!u(Lb,b)){var h=b.lastIndexOf(Qb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Rb+a)}q[Pb]=c;return b||Mb};l[Lb]={'default':0,it_IT:1};m[Sb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Tb)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1&&r.documentMode>=10}())return Wb;if(function(){return b.indexOf(Vb)!=-1&&r.documentMode>=9}())return Xb;if(function(){return b.indexOf(Vb)!=-1&&r.documentMode>=8}())return Yb;if(function(){return b.indexOf(Zb)!=-1}())return $b;return _b};l[Sb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};u=function(a,b){return b in l[a]};mercatino.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};mercatino.__computePropValue=n;q.__gwt_activeModules[W].bindings=mercatino.__getPropMap;t(S,ac);if(s()){return I(bc)}var o;try{k([Mb,Ub],cc);k([Mb,$b],dc);k([Mb,Xb],ec);k([fc,Xb],gc);k([fc,Yb],hc);k([fc,Ub],ic);k([Mb,Wb],jc);k([Mb,Yb],kc);k([fc,$b],lc);k([fc,Wb],mc);o=i[n(Lb)][n(Sb)];var p=o.indexOf(nc);if(p!=-1){j=parseInt(o.substring(p+1),10);o=o.substring(0,p)}}catch(a){}mercatino.__softPermutationId=j;return I(o+oc)}
function K(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(pc);b.setAttribute(qc,rc);b.setAttribute(sc,I(a));r.getElementsByTagName(pb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(tc,T);c(uc);t(tc,vc)}
G();mercatino.__moduleBase=H();w[W].moduleBase=mercatino.__moduleBase;var L=J();if(q){var M=!!(q.location.protocol==wc||q.location.protocol==xc);q.__gwt_activeModules[W].canRedirect=M;function N(){var b=yc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(M&&N()){var O=zc;var P=q.sessionStorage[O];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(P)){if(P&&(window.console&&console.log)){console.log(Ac+P)}P=eb}if(P&&!q[O]){q[O]=true;q[O+Bc]=H();var Q=r.createElement(lb);Q.src=P;var R=r.getElementsByTagName(pb)[0];R.insertBefore(Q,R.firstElementChild||R.children[0]);return false}}}K();t(S,vc);F(L);return true}
mercatino.succeeded=mercatino();if (!window.__gwt_scriptsLoaded) window.__gwt_scriptsLoaded = {};if (!__gwt_scriptsLoaded['sc/modules/ISC_Core.js']) {__gwt_scriptsLoaded['sc/modules/ISC_Core.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_Core.js"></script>');}if (!__gwt_scriptsLoaded['sc/modules/ISC_Foundation.js']) {__gwt_scriptsLoaded['sc/modules/ISC_Foundation.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_Foundation.js"></script>');}if (!__gwt_scriptsLoaded['sc/modules/ISC_Containers.js']) {__gwt_scriptsLoaded['sc/modules/ISC_Containers.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_Containers.js"></script>');}if (!__gwt_scriptsLoaded['sc/modules/ISC_Grids.js']) {__gwt_scriptsLoaded['sc/modules/ISC_Grids.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_Grids.js"></script>');}if (!__gwt_scriptsLoaded['sc/modules/ISC_Forms.js']) {__gwt_scriptsLoaded['sc/modules/ISC_Forms.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_Forms.js"></script>');}if (!__gwt_scriptsLoaded['sc/modules/ISC_RichTextEditor.js']) {__gwt_scriptsLoaded['sc/modules/ISC_RichTextEditor.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_RichTextEditor.js"></script>');}if (!__gwt_scriptsLoaded['sc/modules/ISC_Calendar.js']) {__gwt_scriptsLoaded['sc/modules/ISC_Calendar.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_Calendar.js"></script>');}if (!__gwt_scriptsLoaded['sc/modules/ISC_DataBinding.js']) {__gwt_scriptsLoaded['sc/modules/ISC_DataBinding.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/modules/ISC_DataBinding.js"></script>');}if (!__gwt_scriptsLoaded['sc/skins/Enterprise/load_skin.js']) {__gwt_scriptsLoaded['sc/skins/Enterprise/load_skin.js'] = true;document.write('<script language="javascript" src="'+mercatino.__moduleBase+'sc/skins/Enterprise/load_skin.js"></script>');}